www/routes/web.php
<?php

use App\Http\Controllers\Admin\OptionController;
use Illuminate\Support\Facades\App as Locale;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Models\Page;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
$locale = Locale::currentLocale();

Auth::routes(['register' => false]);
Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

Route::group(['prefix' => '{locale?}', 'middleware' => 'locale'], function ($locale) {
    Route::get('', [App\Http\Controllers\PageController::class, 'index'])->name('index');
    Route::get('/about', [App\Http\Controllers\PageController::class, 'about'])->name('about');
    Route::post('/about/review/add',
        [\App\Http\Controllers\PageController::class, 'createReview'])->name('review.create');
    Route::get('/download/{file}',
        [App\Http\Controllers\PageController::class, 'aboutGetFile'])->name('about.get-file');
    Route::get('/event', [App\Http\Controllers\PageController::class, 'event'])->name('event');

    Route::get('/mconsult', [App\Http\Controllers\PageController::class, 'mconsult'])->name('mconsult');
    Route::get('/registration-and-accreditation',
        [\App\Http\Controllers\PageController::class, 'registrationAccreditation'])->name('accreditation');
    Route::get('/relocation-services', [\App\Http\Controllers\PageController::class, 'relocation'])->name('relocation');
    Route::get('/travel-and-leisure', [\App\Http\Controllers\PageController::class, 'travel'])->name('travel');
    Route::get('/visa-support', [\App\Http\Controllers\PageController::class, 'visa'])->name('visa');
    Route::get('/{number}/inner',
        [App\Http\Controllers\PageController::class, 'mconsultInner'])->name('mconsult-inner');
    Route::get('/sale/{number}',
        [App\Http\Controllers\PageController::class, 'mconsultSale'])->name('mconsult.sale');
    Route::get('/news', [App\Http\Controllers\PageController::class, 'news'])->name('news');
    Route::get('/publication', [App\Http\Controllers\PageController::class, 'publication'])->name('publication');
    Route::get('/sale', [App\Http\Controllers\PageController::class, 'sale'])->name('sale');

    Route::group(['prefix' => '/inform-agency', 'as' => 'inform-agency.'], function ($locale) {
        Route::get('', [App\Http\Controllers\InformAgency\PageController::class, 'index'])->name('index');
        Route::get('/news', [App\Http\Controllers\InformAgency\PageController::class, 'news'])->name('news');
        Route::get('/publications',
            [App\Http\Controllers\InformAgency\PageController::class, 'publications'])->name('publications');
        Route::get('/events', [App\Http\Controllers\InformAgency\PageController::class, 'events'])->name('events');
        Route::get('/inform-agency/{type}/{agency}',
            [App\Http\Controllers\InformAgency\PageController::class, 'item'])->name('item');
    });
    Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('show.login');
});

Route::get('{locale?}/admin', function () {
    return redirect()->route('admin.main.index');
});

Route::get('/admin', function () {
    return redirect()->route('admin.main.index');
});

Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => '/main', 'as' => 'main.'], function () {
        Route::get('', [App\Http\Controllers\Admin\MainController::class, 'index'])->name('index');
        Route::post('text/store/{lang}',
            [App\Http\Controllers\Admin\MainController::class, 'textStore'])->name('store');
        Route::post('/clients/store',
            [App\Http\Controllers\Admin\MainController::class, 'clientStore'])->name('clients.store');
        Route::get('/clients/{client}',
            [App\Http\Controllers\Admin\MainController::class, 'clientEdit'])->name('clients.edit');
        Route::post('/clients/{client}/update',
            [App\Http\Controllers\Admin\MainController::class, 'clientUpdate'])->name('clients.update');
        Route::post('/clients/{client}/delete',
            [App\Http\Controllers\Admin\MainController::class, 'clientDelete'])->name('clients.delete');
    });

    Route::group(['prefix' => '/about-us', 'as' => 'about.'], function () {
        Route::get('', [App\Http\Controllers\Admin\AboutController::class, 'index'])->name('index');
        Route::post('/meta/store/{lang}',
            [App\Http\Controllers\Admin\AboutController::class, 'metaStore'])->name('meta.store');
        Route::group(['prefix' => '/reviews', 'as' => 'reviews.'], function () {
            Route::get('/{review}',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewEdit'])->name('edit');
            Route::post('/{review}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewUpdate'])->name('update');
            Route::delete('/{review}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewDelete'])->name('delete');
        });
        Route::group(['prefix' => '/team', 'as' => 'team.'], function () {
            Route::get('/{team}',
                [App\Http\Controllers\Admin\AboutController::class, 'teamEdit'])->name('edit');
            Route::post('/{team}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'teamUpdate'])->name('update');
            Route::delete('/{team}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'teamDelete'])->name('delete');
        });
        Route::group(['prefix' => '/certificate', 'as' => 'certificate.'], function () {
            Route::get('/add',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateAdd'])->name('add');
            Route::post('/store',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateStore'])->name('store');
            Route::get('/{certificate}',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateEdit'])->name('edit');
            Route::post('/{certificate}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateUpdate'])->name('update');
            Route::delete('/{certificate}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateDelete'])->name('delete');
        });
    });

    Route::group(['prefix' => '/'.Page::PAGE_SRVM, 'as' => 'srvm.'], function () {
        Route::get('', [App\Http\Controllers\Admin\SRVMController::class, 'index'])->name('index');
    });;
    Route::group(['prefix' => '/'.Page::PAGE_VISA_SUPPORT, 'as' => 'visa.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\VisaSupportController::class, 'index'])->name('index');
        Route::get('{country}/edit',
            [\App\Http\Controllers\Admin\CountryController::class, 'edit'])->name('country.edit');
        Route::post('{country}/update',
            [\App\Http\Controllers\Admin\CountryController::class, 'update'])->name('country.update');
        Route::post('country/store',
            [\App\Http\Controllers\Admin\CountryController::class, 'store'])->name('country.store');
    });

    Route::group(['prefix' => '/'.Page::PAGE_RELOCATION, 'as' => 'relocation.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\RelocationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_REGISTRY_ACCREDITATION, 'as' => 'accreditation.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\RegitstryAccreditationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_TRAVEL_RELAXATION, 'as' => 'travel.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\TravelRelaxationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_INFORM_AGENCY, 'as' => 'agency.'], function () {
        Route::get('', [App\Http\Controllers\Admin\InformAgencyController::class, 'index'])->name('index');
        Route::get('{number}', [\App\Http\Controllers\Admin\InformAgencyController::class, 'edit'])->name('edit');
        Route::post('{agency}/update',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'update'])->name('update');
        Route::post('{number}/image/update',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'updateImage'])->name('update.image');
        Route::get('{number}/{type}/add',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'add'])->name('add');
        Route::post('create', [\App\Http\Controllers\Admin\InformAgencyController::class, 'create'])->name('create');
    });

    Route::group(['prefix' => '/options', 'as' => 'option.'], function () {
        Route::get('', [App\Http\Controllers\Admin\OptionController::class, 'index'])->name('index');
        Route::get('{key}/edit', [App\Http\Controllers\Admin\OptionController::class, 'edit'])->name('edit');

        Route::post('{key}/update', [App\Http\Controllers\Admin\OptionController::class, 'update'])->name('update');
    });

    Route::get('/information-support',
        [App\Http\Controllers\Admin\PageController::class, 'informationSupport'])->name('information-support');
    Route::get('/luxembourg', [App\Http\Controllers\Admin\PageController::class, 'luxembourg'])->name('luxembourg');
    Route::get('/package-services',
        [App\Http\Controllers\Admin\PageController::class, 'packageServices'])->name('package-services');

www/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

www/resources/views/layouts/head.blade.php
@include('layouts.version')

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta charset="utf-8">
<base href="{{ url('/') }}">
@if(isset($page))
    <meta name="description" content="{{ $page->description_meta }}">
    <meta name="author" content="{{ $page->title_meta }}">
    <meta name="keywords" content="{{ $page->keywords_meta }}">

    <meta property="og:locale" content="{{ $locale }}" />
    <meta property="og:type" content="website"/>
    <meta property="og:site_name" content="Конфиденс Групп" />
    <meta property="og:title" content="{{ $page->title_meta }}" />
    <meta property="og:description" content="{{ $page->description_meta }}" />
    <meta property="og:url" content="{{ url('/') }}" />
    <meta property="og:image" content="images/icons/confidence-og.png" />

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="{{ $metaOptions['twitter_account_meta']->value }}">
    <meta name="twitter:title" content="{{ $page->title_meta }}">
    <meta name="twitter:description" content="{{ $page->description_meta }}">
    <meta name="twitter:image" content="images/icons/confidence-og.png">
@endif

<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Corporation",
    "name": "Конфиденс Групп",
    "url": "{{ url('/') }}",
    "logo": "images/icons/speeddial-160px.png",
    "alternateName": "Конфиденс",
    "sameAs": [
        "{{ $metaOptions['twitter_url_meta']->value }}",
        "{{ $metaOptions['facebook_url_meta']->value }}",
        "{{ $metaOptions['instagram_url_meta']->value }}",
        "{{ $metaOptions['linkedin_url_meta']->value }}",
    ],
    "contactPoint": [
        {
            "@type": "ContactPoint",
            "telephone": "{{ $metaOptions['phone_number_meta']->value }}",
            "contactType": "technical support",
            "email": "{{ $metaOptions['email_technical_support_meta']->value }}",
            "availableLanguage": [
                "en",
                "ru"
            ]
        }
    ]
}
</script>
<meta http-equiv="content-language" content="{{ $locale }}">
<link rel="icon" type="image/x-icon" href="images/icons/favicon.ico" />
<link rel="icon" href="images/icons/icon.svg" sizes="any" type="image/svg+xml">
<link rel="icon" href="images/icons/favicon-16.png" sizes="16x16" type="image/png">
<link rel="icon" href="images/icons/favicon-32.png" sizes="32x32" type="image/png">
<link rel="icon" type="image/png" href="images/icons/speeddial-160px.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/icons/apple-touch-icon-114x114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/icons/apple-touch-icon-72x72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/ !images/icons/apple-touch-icon-57x57-precomposed.png|thumbnail!!images/icons/apple-touch-icon-72x72-precomposed.png|thumbnail!  !images/icons/speeddial-160px.png|thumbnail!  !images/icons/apple-touch-icon-114x114-precomposed.png|thumbnail!  [^favicon.ico] images/icons/apple-touch-icon-57x57-precomposed.png">

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="">

www/resources/views/layouts/inform-agency.blade.php
<!DOCTYPE html>
<html lang="{{ $locale }}">
<head>
    @include('layouts.head')
    <title>@lang('pages.agency.name')</title>
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <link rel="stylesheet" href="{{ asset('css/inform-agency.css') }}">
</head>
<body>
<header class="header">
    <div class="header__inner">
        <div class="header__left">
            <a class="logo" href="/"></a>
        </div>
        <div class="header__mid">
            <nav>
                <ul class="header__nav">
                    <li>
                        <a href="{{ route('inform-agency.news', ['locale' => $locale]) }}#news">@lang('pages.news')</a>
                    </li>
                    <li>
                        <a href="{{ route('inform-agency.publications', ['locale' => $locale]) }}#publication">@lang('pages.publications')</a>
                    </li>
                    <li>
                        <a href="{{ route('inform-agency.events', ['locale' => $locale]) }}#event">@lang('pages.events')</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="header__right">

            <div class="header-options">
                <a href="#" class="header-option header-option--geo open-modal" data-modal="modal-geo">Москва</a>
                <a href="#" class="header-option header-option--search">@lang('pages.search')</a>
                @if($locale == 'ru')
                    <a class="header-option header-option--lang"
                       href="{{\App\Helper::changeLang('en')}}">@lang('pages.lang')</a>
                @else
                    <a class="header-option header-option--lang"
                       href="{{\App\Helper::changeLang('ru')}}">@lang('pages.lang')</a>
                @endif
            </div>

            <a class="menu-btn-mobile">
                <span class="top"></span>
                <span class="middle"></span>
                <span class="bottom"></span>
            </a>
        </div>
    </div>
</header>

<section class="content">
    <section class="hero-search">
        <picture>
            <source media="(min-width: 1440px)" srcset="{{ asset('images/1440/inform-agency-inner-1440.webp') }}">
            <source media="(min-width: 1280px)" srcset="{{ asset('images/1280/inform-agency-inner-1280.webp') }}">
            <source media="(min-width: 768px)" srcset="{{ asset('images/768/inform-agency-inner-768.webp') }}">
            <source media="(min-width: 564px)" srcset="{{ asset('images/564/inform-agency-inner-564.webp') }}">
            <source media="(min-width: 0px)" srcset="{{ asset('images/400/inform-agency-inner-400.webp') }}">
            <img class="image-fallback" src="{{ asset('images/768/inform-agency-inner-768.jpg') }}"
                 srcset="{{ asset('images/1440/inform-agency-inner-1440.jpg') }} 2x" alt="hero-search">
        </picture>
        <div class="hero-search__inner">
            <div class="hero-search__title title">
                <h1>
                    @lang('pages.agency.name')
                </h1>
            </div>
            <form class="search-field">
                <input type="text" class="search-field__input" placeholder="@lang('pages.agency.search_form.interested')">
                <button class="search-field__reset" type="reset"></button>
                <button class="search-field__submit title" type="submit">@lang('pages.agency.search_form.search')</button>
            </form>
        </div>
    </section>
    @yield('content')
</section>

<div class="bottom-nav" style="bottom: 0px;">
    <a href="#" class="bell"></a>
    <a href="#" class="next"></a>
</div>

@php
    if ($locale == 'ru') {
        $lang = \App\Models\Page::LANGUAGE_RU;
    } else {
        $lang = \App\Models\Page::LANGUAGE_ENG;
    }
       $footer_info = \App\Models\MainPage::where('language', $lang)->first();
@endphp

<footer class="footer-sub">
    <div class="footer-sub__inner">
        <picture>
            <source media="(min-width: 1440px)"
                    srcset="{{ asset('images/1440/subscripbe-1440.webp, images/1440/subscripbe-1440.jpg') }}">
            <source media="(min-width: 1280px)"
                    srcset="{{ asset('images/1280/subscripbe-1280.webp') }}, {{ asset('images/1280/subscripbe-1280.jpg') }}">
            <source media="(min-width: 768px)"
                    srcset="{{ asset('images/768/subscripbe-768.webp, images/768/subscripbe-768.jpg') }}">
            <source media="(min-width: 564px)"
                    srcset="{{ asset('images/564/subscripbe-564.webp, images/564/subscripbe-564.jpg') }}">
            <source media="(min-width: 0px)"
                    srcset="{{ asset('images/400/subscripbe-400.webp') }}, {{ asset('images/400/subscripbe-400.jpg') }}">
            <img class="image-fallback" src="{{ asset('images/768/subscripbe-768.jpg') }}" alt="footer-bg">
        </picture>
        <div class="footer-sub__title title">
            <h2>@lang('pages.agency.footer.subscribe_for_information')</h2>
        </div>
        <div class="footer-sub__desc">
            <p class="red">@lang('pages.agency.footer.actual_events')</p>
        </div>
        <form action="" class="footer-sub__form">
            <div class="footer-sub__row">
                <input class="footer-sub__input" type="text" placeholder="@lang('pages.agency.footer.name')">
                <input class="footer-sub__input" type="email" placeholder="E-MAIL">
            </div>
            <button class="footer-sub__submit btn">@lang('pages.agency.footer.subscribe')</button>
        </form>
        <div class="soc">
            <a href="{{ $metaOptions['twitter_url_meta']->value }}" class="soc__link soc__link--tw"></a>
            <a href="{{ $metaOptions['facebook_url_meta']->value }}" class="soc__link soc__link--fb"></a>
            <a href="{{ $metaOptions['linkedin_url_meta']->value }}" class="soc__link soc__link--in"></a>
            <a href="{{ $metaOptions['vkontakte_url_meta']->value }}" class="soc__link soc__link--vk"></a>
        </div>
        <p class="footer-sub__extra">
            @lang('pages.agency.footer.information')
        </p>

    </div>
    <div class="footer__bot">
        @lang('pages.footer.rights')
    </div>
</footer>

<!-- MODALS -->
<div class="popup-form" id="modal-geo">
    <div class="inner">
        <div class="close close-modal" data-modal="modal-geo"></div>
        <div class="title big">@lang('pages.current_region')<br><span class="red">Moscow</span></div>
        <!--
        <div class="btn"><a href="#">Change region</a></div>
         -->
    </div>
</div>
<!-- /MODALS -->
<script src="{{ asset('libs/jquery-3.4.1.min.js') }}"></script>
<script src="{{ asset('libs/slick.min.js') }}"></script>
<script src="{{ asset('libs/simplaLightbox/simpleLightbox.min.js') }}"></script>
<script src="{{ asset('js/main.js') }}"></script>
<script src="{{ asset('js/scroll-anchors.js') }}"></script>
<script src="{{ asset('js/animation.js') }}"></script>
<script src="{{ asset('js/sticky.js') }}"></script>
<script src="{{ asset('js/custom.js') }}"></script>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
      rel="stylesheet">
</body>
</html>

www/resources/views/layouts/version.blade.php
<!-- Assembly version:	release 1.2 -->