www/routes/web.php
<?php

use App\Http\Controllers\Admin\OptionController;
use Illuminate\Support\Facades\App as Locale;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Models\Page;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
$locale = Locale::currentLocale();

Auth::routes(['register' => false]);
Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

Route::group(['prefix' => '{locale?}', 'middleware' => 'locale'], function ($locale) {
    Route::get('', [App\Http\Controllers\PageController::class, 'index'])->name('index');
    Route::get('/about', [App\Http\Controllers\PageController::class, 'about'])->name('about');
    Route::post('/about/review/add',
        [\App\Http\Controllers\PageController::class, 'createReview'])->name('review.create');
    Route::get('/download/{file}',
        [App\Http\Controllers\PageController::class, 'aboutGetFile'])->name('about.get-file');
    Route::get('/event', [App\Http\Controllers\PageController::class, 'event'])->name('event');

    Route::get('/mconsult', [App\Http\Controllers\PageController::class, 'mconsult'])->name('mconsult');
    Route::get('/registration-and-accreditation',
        [\App\Http\Controllers\PageController::class, 'registrationAccreditation'])->name('accreditation');
    Route::get('/relocation-services', [\App\Http\Controllers\PageController::class, 'relocation'])->name('relocation');
    Route::get('/travel-and-leisure', [\App\Http\Controllers\PageController::class, 'travel'])->name('travel');
    Route::get('/visa-support', [\App\Http\Controllers\PageController::class, 'visa'])->name('visa');
    Route::get('/{number}/inner',
        [App\Http\Controllers\PageController::class, 'mconsultInner'])->name('mconsult-inner');
    Route::get('/sale/{number}',
        [App\Http\Controllers\PageController::class, 'mconsultSale'])->name('mconsult.sale');
    Route::get('/news', [App\Http\Controllers\PageController::class, 'news'])->name('news');
    Route::get('/publication', [App\Http\Controllers\PageController::class, 'publication'])->name('publication');
    Route::get('/sale', [App\Http\Controllers\PageController::class, 'sale'])->name('sale');

    Route::group(['prefix' => '/inform-agency', 'as' => 'inform-agency.'], function ($locale) {
        Route::get('', [App\Http\Controllers\InformAgency\PageController::class, 'index'])->name('index');
        Route::get('/news', [App\Http\Controllers\InformAgency\PageController::class, 'news'])->name('news');
        Route::get('/publications',
            [App\Http\Controllers\InformAgency\PageController::class, 'publications'])->name('publications');
        Route::get('/events', [App\Http\Controllers\InformAgency\PageController::class, 'events'])->name('events');
        Route::get('/inform-agency/{type}/{agency}',
            [App\Http\Controllers\InformAgency\PageController::class, 'item'])->name('item');
    });
    Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('show.login');
});

Route::get('{locale?}/admin', function () {
    return redirect()->route('admin.main.index');
});

Route::get('/admin', function () {
    return redirect()->route('admin.main.index');
});

Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => '/main', 'as' => 'main.'], function () {
        Route::get('', [App\Http\Controllers\Admin\MainController::class, 'index'])->name('index');
        Route::post('text/store/{lang}',
            [App\Http\Controllers\Admin\MainController::class, 'textStore'])->name('store');
        Route::post('/clients/store',
            [App\Http\Controllers\Admin\MainController::class, 'clientStore'])->name('clients.store');
        Route::get('/clients/{client}',
            [App\Http\Controllers\Admin\MainController::class, 'clientEdit'])->name('clients.edit');
        Route::post('/clients/{client}/update',
            [App\Http\Controllers\Admin\MainController::class, 'clientUpdate'])->name('clients.update');
        Route::post('/clients/{client}/delete',
            [App\Http\Controllers\Admin\MainController::class, 'clientDelete'])->name('clients.delete');
    });

    Route::group(['prefix' => '/about-us', 'as' => 'about.'], function () {
        Route::get('', [App\Http\Controllers\Admin\AboutController::class, 'index'])->name('index');
        Route::post('/meta/store/{lang}',
            [App\Http\Controllers\Admin\AboutController::class, 'metaStore'])->name('meta.store');
        Route::group(['prefix' => '/reviews', 'as' => 'reviews.'], function () {
            Route::get('/{review}',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewEdit'])->name('edit');
            Route::post('/{review}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewUpdate'])->name('update');
            Route::delete('/{review}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewDelete'])->name('delete');
        });
        Route::group(['prefix' => '/team', 'as' => 'team.'], function () {
            Route::get('/{team}',
                [App\Http\Controllers\Admin\AboutController::class, 'teamEdit'])->name('edit');
            Route::post('/{team}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'teamUpdate'])->name('update');
            Route::delete('/{team}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'teamDelete'])->name('delete');
        });
        Route::group(['prefix' => '/certificate', 'as' => 'certificate.'], function () {
            Route::get('/add',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateAdd'])->name('add');
            Route::post('/store',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateStore'])->name('store');
            Route::get('/{certificate}',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateEdit'])->name('edit');
            Route::post('/{certificate}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateUpdate'])->name('update');
            Route::delete('/{certificate}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateDelete'])->name('delete');
        });
    });

    Route::group(['prefix' => '/'.Page::PAGE_SRVM, 'as' => 'srvm.'], function () {
        Route::get('', [App\Http\Controllers\Admin\SRVMController::class, 'index'])->name('index');
    });;
    Route::group(['prefix' => '/'.Page::PAGE_VISA_SUPPORT, 'as' => 'visa.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\VisaSupportController::class, 'index'])->name('index');
        Route::get('{country}/edit',
            [\App\Http\Controllers\Admin\CountryController::class, 'edit'])->name('country.edit');
        Route::post('{country}/update',
            [\App\Http\Controllers\Admin\CountryController::class, 'update'])->name('country.update');
        Route::post('country/store',
            [\App\Http\Controllers\Admin\CountryController::class, 'store'])->name('country.store');
    });

    Route::group(['prefix' => '/'.Page::PAGE_RELOCATION, 'as' => 'relocation.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\RelocationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_REGISTRY_ACCREDITATION, 'as' => 'accreditation.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\RegitstryAccreditationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_TRAVEL_RELAXATION, 'as' => 'travel.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\TravelRelaxationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_INFORM_AGENCY, 'as' => 'agency.'], function () {
        Route::get('', [App\Http\Controllers\Admin\InformAgencyController::class, 'index'])->name('index');
        Route::get('{number}', [\App\Http\Controllers\Admin\InformAgencyController::class, 'edit'])->name('edit');
        Route::post('{agency}/update',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'update'])->name('update');
        Route::post('{number}/image/update',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'updateImage'])->name('update.image');
        Route::get('{number}/{type}/add',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'add'])->name('add');
        Route::post('create', [\App\Http\Controllers\Admin\InformAgencyController::class, 'create'])->name('create');
    });

    Route::group(['prefix' => '/options', 'as' => 'option.'], function () {
        Route::get('', [App\Http\Controllers\Admin\OptionController::class, 'index'])->name('index');
        Route::get('{key}/edit', [App\Http\Controllers\Admin\OptionController::class, 'edit'])->name('edit');

        Route::post('{key}/update', [App\Http\Controllers\Admin\OptionController::class, 'update'])->name('update');
    });

    Route::get('/information-support',
        [App\Http\Controllers\Admin\PageController::class, 'informationSupport'])->name('information-support');
    Route::get('/luxembourg', [App\Http\Controllers\Admin\PageController::class, 'luxembourg'])->name('luxembourg');
    Route::get('/package-services',
        [App\Http\Controllers\Admin\PageController::class, 'packageServices'])->name('package-services');

www/resources/views/admin/pages/news-agency/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    @include('admin.partials.sidebar')
    <article class="article">
        @include('admin.partials.header')
        <div class="header__sub">
            <div class="sub header">изменение</div>
            <h1 class="ui header">ИЗМЕНЕНИЕ ДАННЫХ</h1>
            <h2 class="sub header"></h2>
        </div>
    </article>
    <main class="page">
        <section class="main">
            <div class="ui bottom attached tab segment active">
                <div class="sub header">Изменение данных.</div>
                <form action="{{ route('admin.agency.update', ['agency' => $agency_ru->id]) }}" method="POST">
                    @csrf
                    <h3 class="ui header">Содержание</h3>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Описание русское</h4>
                        <div class="sub header header__subheader">Пояснение</div>
                        <textarea class="ui segment textEditor"
                                  name="name">{{ $agency_ru->name }}</textarea>
                    </div>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Описание русское</h4>
                        <div class="sub header header__subheader">Пояснение</div>
                        <textarea class="ui segment textEditor"
                                  name="description">{{ $agency_ru->description }}</textarea>
                        <button type="submit" class="ui blue button">Сохранить</button>
                    </div>
                </form>
                <form action="{{ route('admin.agency.update', ['agency' => $agency_ru->id]) }}" method="POST">
                    @csrf
                    <h3 class="ui header header__subheader">Метаданные русской версии</h3>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Title</h4>
                        <div class="sub header header__subheader">не более 3-5 ключевых слов/словосочетаний</div>
                        <div class="ui input">
                            <input type="text" name="title_meta" value="{{ $agency_ru->title_meta }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Keywords</h4>
                        <div class="sub header header__subheader">70-80 символов</div>
                        <div class="ui input">
                            <input type="text" name="keywords_meta" value="{{ $agency_ru->keywords_meta }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Description</h4>
                        <div class="sub header header__subheader">мета-описание страницы. Для SEO этот тег один из
                            ключевых.
                        </div>
                        <textarea class="ui segment textEditor"
                                  name="description_meta">{{ $agency_ru->description_meta }}</textarea>
                        <button type="submit" class="ui blue button">Сохранить</button>
                    </div>
                </form>

                <img class="page__img" src="{{ asset($agency_ru->background_image) }}" alt=""/>
                <form action="{{ route('admin.agency.update.image', ['number' => $agency_ru->number]) }}" method="POST"
                      enctype="multipart/form-data">
                    @csrf
                    <div class="ui action input">
                        <input type="text" placeholder="Загрузить файл"/>
                        <input type="file" name="background_image" required/>
                        <a class="ui blue button fileUpload">Выбрать</a>
                    </div>
                    <button type="submit" class="ui blue button">Сохранить</button>
                </form>

                <form action="{{ route('admin.agency.update', ['agency' => $agency_eng->id]) }}" method="POST">
                    @csrf
                    <h3 class="ui header">Содержание английской версии</h3>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Описание английское</h4>
                        <div class="sub header header__subheader">Пояснение</div>
                        <textarea class="ui segment textEditor"
                                  name="name">{{ $agency_eng->name }}</textarea>
                    </div>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Описание английское</h4>
                        <div class="sub header header__subheader">Пояснение</div>
                        <textarea class="ui segment textEditor"
                                  name="description">{{ $agency_eng->description }}</textarea>
                        <button type="submit" class="ui blue button">Сохранить</button>
                    </div>
                </form>
                <form action="{{ route('admin.agency.update', ['agency' => $agency_eng->id]) }}" method="POST">
                    @csrf
                    <h3 class="ui header header__subheader">Метаданные английской версии</h3>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Title</h4>
                        <div class="sub header header__subheader">не более 3-5 ключевых слов/словосочетаний</div>
                        <div class="ui input">
                            <input type="text" name="title_meta" value="{{ $agency_eng->title_meta }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Keywords</h4>
                        <div class="sub header header__subheader">70-80 символов</div>
                        <div class="ui input">
                            <input type="text" name="keywords_meta" value="{{ $agency_eng->keywords_meta }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Description</h4>
                        <div class="sub header header__subheader">мета-описание страницы. Для SEO этот тег один из
                            ключевых.
                        </div>
                        <textarea class="ui segment textEditor"
                                  name="description_meta">{{ $agency_eng->description_meta }}</textarea>
                        <button type="submit" class="ui blue button">Сохранить</button>
                    </div>
                </form>

                <img class="page__img" src="{{ asset($agency_eng->background_image) }}" alt=""/>
                <form action="{{ route('admin.agency.update.image', ['number' => $agency_ru->number]) }}" method="POST"
                      enctype="multipart/form-data">
                    @csrf
                    <div class="ui action input">
                        <input type="text" placeholder="Загрузить файл"/>
                        <input type="file" name="background_image" required/>
                        <a class="ui blue button fileUpload">Выбрать</a>
                    </div>
                    <button type="submit" class="ui blue button">Сохранить</button>
                </form>
            </div>
        </section>
    </main>
@endsection

www/resources/views/admin/pages/news-agency/index.blade.php
@extends('admin.layouts.app')

@section('content')
    @include('admin.partials.sidebar')
    <article class="article">
        @include('admin.partials.header')
        <div class="header__sub">
            <div class="sub header">раздел</div>
            <h1 class="ui header">Информационное агентство</h1>
            <h2 class="sub header">МИГРАЦИОННЫЙ КОНСАЛТИНГ / СПЕЦИАЛЬНЫЕ ПРЕДЛОЖЕНИЯ И АКЦИИ</h2>
            <div class="ui top attached tabular menu">
                <div class="item" data-tab="0">Страница</div>
                <div class="item" data-tab="2">Новости</div>
                <div class="item" data-tab="1">Публикации</div>
                <div class="item" data-tab="3">Мероприятия</div>
            </div>
        </div>
    </article>
    <main class="page">
        <section class="srvm">
            <div class="ui bottom attached tab segment active" data-tab="0">
                <form
                    action="{{ route('admin.page.store', ['page' => $page_ru->category, 'lang' => $page_ru->language]) }}"
                    method="POST">
                    @csrf
                    <h3 class="ui header">Содержание</h3>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Название русское</h4>
                        <div class="sub header header__subheader">Пояснение</div>
                        <div class="ui input">
                            <input type="text" name="name" value="{{ $page_ru->name }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Описание русское</h4>
                        <div class="sub header header__subheader">Пояснение</div>
                        <textarea class="ui segment textEditor"
                                  name="description">{{ $page_ru->description }}</textarea>
                        <button type="submit" class="ui blue button">Сохранить</button>
                    </div>
                </form>
                <form
                    action="{{ route('admin.page.store', ['page' => $page_ru->category, 'lang' => $page_ru->language]) }}"
                    method="POST">
                    @csrf
                    <h3 class="ui header header__subheader">Метаданные русской версии</h3>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Title</h4>
                        <div class="sub header header__subheader">не более 3-5 ключевых слов/словосочетаний</div>
                        <div class="ui input">
                            <input type="text" name="title_meta" value="{{ $page_ru->title_meta }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Keywords</h4>
                        <div class="sub header header__subheader">70-80 символов</div>
                        <div class="ui input">
                            <input type="text" name="keywords_meta" value="{{ $page_ru->keywords_meta }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Description</h4>
                        <div class="sub header header__subheader">мета-описание страницы. Для SEO этот тег один из
                            ключевых.
                        </div>
                        <textarea class="ui segment textEditor"
                                  name="description_meta">{{ $page_ru->description_meta }}</textarea>
                        <button type="submit" class="ui blue button">Сохранить</button>
                    </div>
                </form>
                <form
                    action="{{ route('admin.page.store', ['page' => $page_eng->category, 'lang' => $page_eng->language]) }}"
                    method="POST">
                    @csrf
                    <h3 class="ui header">Содержание английской версии</h3>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Название английское</h4>
                        <div class="sub header header__subheader">Пояснение</div>
                        <div class="ui input">
                            <input type="text" name="name" value="{{ $page_eng->name }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Описание английское</h4>
                        <div class="sub header header__subheader">Пояснение</div>
                        <textarea class="ui segment textEditor"
                                  name="description">{{ $page_eng->description }}</textarea>
                        <button type="submit" class="ui blue button">Сохранить</button>
                    </div>
                </form>
                <form
                    action="{{ route('admin.page.store', ['page' => $page_eng->category, 'lang' => $page_eng->language]) }}"
                    method="POST">
                    @csrf
                    <h3 class="ui header header__subheader">Метаданные английской версии</h3>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Title</h4>
                        <div class="sub header header__subheader">не более 3-5 ключевых слов/словосочетаний</div>
                        <div class="ui input">
                            <input type="text" name="title_meta" value="{{ $page_eng->title_meta }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleInputText">
                        <h4 class="ui header header__subtitle">Keywords</h4>
                        <div class="sub header header__subheader">70-80 символов</div>
                        <div class="ui input">
                            <input type="text" name="keywords_meta" value="{{ $page_eng->keywords_meta }}"/>
                        </div>
                    </div>
                    <div class="page-block-titleAreaText">
                        <h4 class="ui header header__subtitle">Description</h4>
                        <div class="sub header header__subheader">мета-описание страницы. Для SEO этот тег один из
                            ключевых.
                        </div>
                        <textarea class="ui segment textEditor"
                                  name="description_meta">{{ $page_eng->description_meta }}</textarea>
                        <button type="submit" class="ui blue button">Сохранить</button>
                    </div>
                </form>
            </div>
            <div class="ui bottom attached tab segment" data-tab="1">
                <h3 class="ui header">Публикации</h3>
                <a href="{{ route('admin.agency.add', ['number' => 1, 'type' => 'publications']) }}" class="ui blue button">+ Добавить</a>
                <div class="ui positive message page__icon_info-positive">Управлять последовательностью иллюстрации в
                    слайдах можно перетаскиванием строк в таблицах.
                </div>
                <table class="ui celled table">
                    <thead>
                    <tr>
                        <th> №</th>
                        <th> ID</th>
                        <th>Название</th>
                        <th>Дата</th>
                        <th>Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($publications as $publication)
                        <tr>
                            <td data-label="Count">{{ $publication->number }}</td>
                            <td data-label="id">{{ $publication->id }}</td>
                            <td data-label="Name">{{ $publication->name }}</td>
                            <td data-label="Date">{{ $publication->updated_at }}</td>
                            <td data-label="Action">
                                <a href="{{ route('admin.agency.edit', ['number' => $publication->number]) }}"
                                   class="page__icon page__icon_pen"></a>
                                <button class="page__icon page__icon_eye"></button>
                                <button class="page__icon page__icon_nolink"></button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="ui bottom attached tab segment" data-tab="2">
                <h3 class="ui header">Новости</h3>
                <a href="{{ route('admin.agency.add', ['number' => 1, 'type' => 'news']) }}" class="ui blue button">+ Добавить</a>
                <div class="ui positive message page__icon_info-positive">Управлять последовательностью иллюстрации в
                    слайдах можно перетаскиванием строк в таблицах.
                </div>
                <table class="ui celled table">
                    <thead>
                    <tr>
                        <th> №</th>
                        <th> ID</th>
                        <th>Название</th>
                        <th>Дата</th>
                        <th>Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($news as $item)
                        <tr>
                            <td data-label="Count">{{ $item->number }}</td>
                            <td data-label="id">{{ $item->id }}</td>
                            <td data-label="Name">{{ $item->name }}</td>
                            <td data-label="Date">{{ $item->updated_at }}</td>
                            <td data-label="Action">
                                <a href="{{ route('admin.agency.edit', ['number' => $item->number]) }}"
                                   class="page__icon page__icon_pen"></a>
                                <button class="page__icon page__icon_eye"></button>
                                <button class="page__icon page__icon_nolink"></button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="ui bottom attached tab segment" data-tab="3">
                <h3 class="ui header">Мероприятия</h3>
                <a href="{{ route('admin.agency.add', ['number' => 1, 'type' => 'events']) }}" class="ui blue button">+ Добавить</a>
                <div class="ui positive message page__icon_info-positive">Управлять последовательностью иллюстрации в
                    слайдах можно перетаскиванием строк в таблицах.
                </div>
                <table class="ui celled table">
                    <thead>
                    <tr>
                        <th> №</th>
                        <th> ID</th>
                        <th>Название</th>
                        <th>Дата</th>
                        <th>Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($events as $event)
                        <tr>
                            <td data-label="Count">{{ $event->number }}</td>
                            <td data-label="id">{{ $event->id }}</td>
                            <td data-label="Name">{{ $event->name }}</td>
                            <td data-label="Date">{{ $event->updated_at }}</td>
                            <td data-label="Action">
                                <a href="{{ route('admin.agency.edit', ['number' => $event->number]) }}"
                                   class="page__icon page__icon_pen"></a>
                                <button class="page__icon page__icon_eye"></button>
                                <button class="page__icon page__icon_nolink"></button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </main>
@endsection