www/routes/web.php
<?php

use App\Http\Controllers\Admin\OptionController;
use Illuminate\Support\Facades\App as Locale;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Models\Page;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
$locale = Locale::currentLocale();

Auth::routes(['register' => false]);
Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

Route::group(['prefix' => '{locale?}', 'middleware' => 'locale'], function ($locale) {
    Route::get('', [App\Http\Controllers\PageController::class, 'index'])->name('index');
    Route::get('/about', [App\Http\Controllers\PageController::class, 'about'])->name('about');
    Route::post('/about/review/add',
        [\App\Http\Controllers\PageController::class, 'createReview'])->name('review.create');
    Route::get('/download/{file}',
        [App\Http\Controllers\PageController::class, 'aboutGetFile'])->name('about.get-file');
    Route::get('/event', [App\Http\Controllers\PageController::class, 'event'])->name('event');

    Route::get('/mconsult', [App\Http\Controllers\PageController::class, 'mconsult'])->name('mconsult');
    Route::get('/registration-and-accreditation',
        [\App\Http\Controllers\PageController::class, 'registrationAccreditation'])->name('accreditation');
    Route::get('/relocation-services', [\App\Http\Controllers\PageController::class, 'relocation'])->name('relocation');
    Route::get('/travel-and-leisure', [\App\Http\Controllers\PageController::class, 'travel'])->name('travel');
    Route::get('/visa-support', [\App\Http\Controllers\PageController::class, 'visa'])->name('visa');
    Route::get('/{number}/inner',
        [App\Http\Controllers\PageController::class, 'mconsultInner'])->name('mconsult-inner');
    Route::get('/sale/{number}',
        [App\Http\Controllers\PageController::class, 'mconsultSale'])->name('mconsult.sale');
    Route::get('/news', [App\Http\Controllers\PageController::class, 'news'])->name('news');
    Route::get('/publication', [App\Http\Controllers\PageController::class, 'publication'])->name('publication');
    Route::get('/sale', [App\Http\Controllers\PageController::class, 'sale'])->name('sale');

    Route::group(['prefix' => '/inform-agency', 'as' => 'inform-agency.'], function ($locale) {
        Route::get('', [App\Http\Controllers\InformAgency\PageController::class, 'index'])->name('index');
        Route::get('/news', [App\Http\Controllers\InformAgency\PageController::class, 'news'])->name('news');
        Route::get('/publications',
            [App\Http\Controllers\InformAgency\PageController::class, 'publications'])->name('publications');
        Route::get('/events', [App\Http\Controllers\InformAgency\PageController::class, 'events'])->name('events');
        Route::get('/inform-agency/{type}/{agency}',
            [App\Http\Controllers\InformAgency\PageController::class, 'item'])->name('item');
    });
    Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('show.login');
});

Route::get('{locale?}/admin', function () {
    return redirect()->route('admin.main.index');
});

Route::get('/admin', function () {
    return redirect()->route('admin.main.index');
});

Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => '/main', 'as' => 'main.'], function () {
        Route::get('', [App\Http\Controllers\Admin\MainController::class, 'index'])->name('index');
        Route::post('text/store/{lang}',
            [App\Http\Controllers\Admin\MainController::class, 'textStore'])->name('store');
        Route::post('/clients/store',
            [App\Http\Controllers\Admin\MainController::class, 'clientStore'])->name('clients.store');
        Route::get('/clients/{client}',
            [App\Http\Controllers\Admin\MainController::class, 'clientEdit'])->name('clients.edit');
        Route::post('/clients/{client}/update',
            [App\Http\Controllers\Admin\MainController::class, 'clientUpdate'])->name('clients.update');
        Route::post('/clients/{client}/delete',
            [App\Http\Controllers\Admin\MainController::class, 'clientDelete'])->name('clients.delete');
    });

    Route::group(['prefix' => '/about-us', 'as' => 'about.'], function () {
        Route::get('', [App\Http\Controllers\Admin\AboutController::class, 'index'])->name('index');
        Route::post('/meta/store/{lang}',
            [App\Http\Controllers\Admin\AboutController::class, 'metaStore'])->name('meta.store');
        Route::group(['prefix' => '/reviews', 'as' => 'reviews.'], function () {
            Route::get('/{review}',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewEdit'])->name('edit');
            Route::post('/{review}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewUpdate'])->name('update');
            Route::delete('/{review}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewDelete'])->name('delete');
        });
        Route::group(['prefix' => '/team', 'as' => 'team.'], function () {
            Route::get('/{team}',
                [App\Http\Controllers\Admin\AboutController::class, 'teamEdit'])->name('edit');
            Route::post('/{team}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'teamUpdate'])->name('update');
            Route::delete('/{team}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'teamDelete'])->name('delete');
        });
        Route::group(['prefix' => '/certificate', 'as' => 'certificate.'], function () {
            Route::get('/add',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateAdd'])->name('add');
            Route::post('/store',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateStore'])->name('store');
            Route::get('/{certificate}',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateEdit'])->name('edit');
            Route::post('/{certificate}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateUpdate'])->name('update');
            Route::delete('/{certificate}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateDelete'])->name('delete');
        });
    });

    Route::group(['prefix' => '/'.Page::PAGE_SRVM, 'as' => 'srvm.'], function () {
        Route::get('', [App\Http\Controllers\Admin\SRVMController::class, 'index'])->name('index');
    });;
    Route::group(['prefix' => '/'.Page::PAGE_VISA_SUPPORT, 'as' => 'visa.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\VisaSupportController::class, 'index'])->name('index');
        Route::get('{country}/edit',
            [\App\Http\Controllers\Admin\CountryController::class, 'edit'])->name('country.edit');
        Route::post('{country}/update',
            [\App\Http\Controllers\Admin\CountryController::class, 'update'])->name('country.update');
        Route::post('country/store',
            [\App\Http\Controllers\Admin\CountryController::class, 'store'])->name('country.store');
    });

    Route::group(['prefix' => '/'.Page::PAGE_RELOCATION, 'as' => 'relocation.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\RelocationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_REGISTRY_ACCREDITATION, 'as' => 'accreditation.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\RegitstryAccreditationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_TRAVEL_RELAXATION, 'as' => 'travel.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\TravelRelaxationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_INFORM_AGENCY, 'as' => 'agency.'], function () {
        Route::get('', [App\Http\Controllers\Admin\InformAgencyController::class, 'index'])->name('index');
        Route::get('{number}', [\App\Http\Controllers\Admin\InformAgencyController::class, 'edit'])->name('edit');
        Route::post('{agency}/update',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'update'])->name('update');
        Route::post('{number}/image/update',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'updateImage'])->name('update.image');
        Route::get('{number}/{type}/add',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'add'])->name('add');
        Route::post('create', [\App\Http\Controllers\Admin\InformAgencyController::class, 'create'])->name('create');
    });

    Route::group(['prefix' => '/options', 'as' => 'option.'], function () {
        Route::get('', [App\Http\Controllers\Admin\OptionController::class, 'index'])->name('index');
        Route::get('{key}/edit', [App\Http\Controllers\Admin\OptionController::class, 'edit'])->name('edit');

        Route::post('{key}/update', [App\Http\Controllers\Admin\OptionController::class, 'update'])->name('update');
    });

    Route::get('/information-support',
        [App\Http\Controllers\Admin\PageController::class, 'informationSupport'])->name('information-support');
    Route::get('/luxembourg', [App\Http\Controllers\Admin\PageController::class, 'luxembourg'])->name('luxembourg');
    Route::get('/package-services',
        [App\Http\Controllers\Admin\PageController::class, 'packageServices'])->name('package-services');

www/app/Http/Controllers/Admin/AboutController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AboutUs\CertificateRequest;
use App\Models\AboutCertificate;
use App\Models\AboutMeta;
use App\Models\AboutReviews;
use App\Models\AboutTeam;
use App\Models\Page;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * PageController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $page_ru = Page::where('category', Page::PAGE_ABOUT)->where('language', Page::LANGUAGE_RU)->first();
        $page_eng = Page::where('category', Page::PAGE_ABOUT)->where('language', Page::LANGUAGE_ENG)->first();
        $meta_ru = AboutMeta::where('language', Page::LANGUAGE_RU)->first();
        $meta_eng = AboutMeta::where('language', Page::LANGUAGE_ENG)->first();
        $reviews_ru = AboutReviews::where('language', Page::LANGUAGE_RU)->get();
        $reviews_eng = AboutReviews::where('language', Page::LANGUAGE_ENG)->get();
        $team = AboutTeam::all();
        $certificates = AboutCertificate::all();

        return view('admin.pages.about.index')->with([
            'page_ru' => $page_ru, 'page_eng' => $page_eng, 'meta_ru' => $meta_ru, 'meta_eng' => $meta_eng,
            'reviews_ru' => $reviews_ru, 'reviews_eng' => $reviews_eng, 'team' => $team, 'certificates' => $certificates
        ]);
    }

    /**
     * @param Request $request
     * @param bool $lang
     * @return \Illuminate\Http\RedirectResponse
     */
    public function metaStore(Request $request, bool $lang)
    {
        $request->request->remove('_token');
        $request['video_link'] = str_replace('watch?v=', 'embed/', $request->video_link);
        if ($request['presentation'] !== null) {

            $fileName = time().'.'.$request->file('presentation')->extension();
            $filePath = $request->file('presentation')->move('presentations', $fileName);
            AboutMeta::where('language', $lang)->update(['presentation' => $filePath->getPathname()]);
        } else {
            AboutMeta::where('language', $lang)->update($request->all());
        }

        return back();
    }

    /**
     * @param AboutReviews $review
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function reviewEdit(AboutReviews $review)
    {
        return view('admin.pages.about.reviews')->with(['review' => $review]);
    }

    /**
     * @param Request $request
     * @param AboutReviews $review
     * @return \Illuminate\Http\RedirectResponse
     */
    public function reviewUpdate(Request $request, AboutReviews $review)
    {
        $review->update($request->all());

        return redirect()->route('admin.about.index');
    }

    /**
     * @param AboutReviews $review
     * @return \Illuminate\Http\RedirectResponse
     */
    public function reviewDelete(AboutReviews $review)
    {
        $review->delete();

        return redirect()->route('admin.about.index');
    }

    /**
     * @param AboutTeam $team
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function teamEdit(AboutTeam $team)
    {
        return view('admin.pages.about.team')->with(['team' => $team]);
    }

    /**
     * @param Request $request
     * @param AboutTeam $team
     * @return \Illuminate\Http\RedirectResponse
     */
    public function teamUpdate(Request $request, AboutTeam $team)
    {
        $image_first = $team->image_first;
        $image_second = $team->image_second;

        if ($request->file('image_first') !== null) {
            $imageName = time().'.'.$request->file('image_first')->extension();
            $image_first = $request->file('image_first')->move('images/team', $imageName);
        }

        if ($request->file('image_second') !== null) {
            $imageName = time().'.'.$request->file('image_second')->extension();
            $image_second = $request->file('image_second')->move('images/team', $imageName);
        }

        $team->update([
            'name_ru' => $request->name_ru,
            'name_eng' => $request->name_eng,
            'image_first' => $image_first,
            'image_second' => $image_second
        ]);

        return redirect()->route('admin.about.index');
    }

    /**
     * @param AboutTeam $team
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function teamDelete(AboutTeam $team)
    {
        $team->delete();

        return redirect()->route('admin.about.index');
    }


    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function certificateAdd()
    {
        return view('admin.pages.about.certificate_add');
    }

    /**
     * @param Request $request
     * @param AboutCertificate $certificate
     * @return \Illuminate\Http\RedirectResponse
     */
    public function certificateStore(CertificateRequest $request)
    {
        $certificate = new AboutCertificate();

        if ($request->file('image') !== null) {
            $imageName = time().'.'.$request->file('image')->extension();
            $image = $request->file('image')->move('images/certificates', $imageName);
        }

        $certificate->name  = $request->name;
        $certificate->image = $image;
        $certificate->save();

        return redirect()->route('admin.about.index');
    }

    /**
     * @param AboutCertificate $certificate
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function certificateEdit(AboutCertificate $certificate)
    {
        return view('admin.pages.about.certificate')->with(['certificate' => $certificate]);
    }

    /**
     * @param Request $request
     * @param AboutCertificate $certificate
     * @return \Illuminate\Http\RedirectResponse
     */
    public function certificateUpdate(CertificateRequest $request, AboutCertificate $certificate)
    {
        $image = $certificate->image;

        if ($request->file('image') !== null) {
            $imageName = time().'.'.$request->file('image')->extension();
            $image = $request->file('image')->move('images/certificates', $imageName);
        }

        $certificate->update([
            'name' => $request->name,
            'image' => $image
        ]);

        return redirect()->route('admin.about.index');
    }

    /**
     * @param AboutTeam $team
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function certificateDelete(AboutCertificate $certificate)
    {
        $certificate->delete();

        return redirect()->route('admin.about.index');
    }
}

www/resources/views/admin/pages/about/certificate.blade.php
@extends('admin.layouts.app')

@section('content')
    @include('admin.partials.sidebar')
    <article class="article">
        @include('admin.partials.header')
        <div class="header__sub">
            <div class="sub header">изменение сертификата</div>
            <h1 class="ui header">ИЗМЕНЕНИЕ СЕРТИФИКАТА {{ $certificate->name }}</h1>
            <h2 class="sub header">
                <span>
                    <a href="{{ route('admin.about.index') }}">О КОМПАНИИ</a>
                    /
                    СЕРТИФИКАТЫ
                    /
                    ИЗМЕНЕНИЕ СЕРТИФИКАТА {{ $certificate->name }}
                </span>
            </h2>
        </div>
    </article>
    <main class="page">
        <section class="main">
            <form action="{{ route('admin.about.certificate.update', ['certificate' => $certificate->id]) }}"
                  method="POST"
                  enctype="multipart/form-data">
                @csrf
                <h3 class="ui header header__title">Содержание</h3>
                <div class="page-block-titleInputText">
                    <h4 class="ui header header__subtitle page__icon_question">Имя автора</h4>
                    <div class="sub header header__subheader">Пояснение</div>
                    <div class="ui input">
                        <input type="text" name="name" value="{{ $certificate->name }}"/>
                    </div>
                </div>
                <img class="page__img" src="{{ asset($certificate->image) }}" alt=""/>
                <div class="sub header header__subheader">Иллюстрацию вписать в габариты 230x153</div>
                <div class="page-block-titleBtnText__btns">
                    <div class="ui action input">
                        <input type="text" placeholder="Загрузить файл"/>
                        <input type="file" name="image"/>
                        <a class="ui blue button fileUpload">Выбрать</a>
                    </div>
                    <button type="submit" class="ui blue button">Обновить</button>
                </div>
                </div>
            </form>
        </section>
    </main>
@endsection

www/resources/views/admin/pages/about/certificate_add.blade.php
@extends('admin.layouts.app')

@section('content')
    @include('admin.partials.sidebar')
    <article class="article">
        @include('admin.partials.header')
        <div class="header__sub">
            <div class="sub header">создание сертификата</div>
            <h1 class="ui header">СОЗДАНИЕ СЕРТИФИКАТА</h1>
            <h2 class="sub header">
                <span>
                    <a href="{{ route('admin.about.index') }}">О КОМПАНИИ</a>
                    /
                    СЕРТИФИКАТЫ
                    /
                    ДОБАВЛЕНИЕ СЕРТИФИКАТА
                </span>
            </h2>
        </div>
    </article>
    <main class="page">
        <section class="main">
            <form action="{{ route('admin.about.certificate.store') }}"
                  method="POST"
                  enctype="multipart/form-data">
                @csrf
                <h3 class="ui header header__title">Содержание</h3>
                <div class="page-block-titleInputText">
                    <h4 class="ui header header__subtitle page__icon_question">Имя автора</h4>
                    <div class="sub header header__subheader">Пояснение</div>
                    <div class="ui input">
                        <input type="text" name="name" value="" required/>
                    </div>
                </div>
                <img class="page__img" src="" alt=""/>
                <div class="sub header header__subheader">Иллюстрацию вписать в габариты 230x153</div>
                <div class="page-block-titleBtnText__btns">
                    <div class="ui action input">
                        <input type="text" placeholder="Загрузить файл"/>
                        <input type="file" name="image" required/>
                        <a class="ui blue button fileUpload">Выбрать</a>
                    </div>
                    <button type="submit" class="ui blue button">Создать</button>
                </div>
                </div>
            </form>
        </section>
    </main>
@endsection

www/resources/views/admin/pages/about/reviews.blade.php
@extends('admin.layouts.app')

@section('content')
    @include('admin.partials.sidebar')
    <article class="article">
        @include('admin.partials.header')
        <div class="header__sub">
            <div class="sub header">изменение отзыва</div>
            <h1 class="ui header">ИЗМЕНЕНИЕ ОТЗЫВА {{ $review->author }}</h1>
            <h2 class="sub header">
                <span>
                    <a href="{{ route('admin.about.index') }}">О КОМПАНИИ</a>
                    /
                    ОТЗЫВЫ
                    /
                    ИЗМЕНЕНИЕ ОТЗЫВА {{ $review->author }}
                </span>
            </h2>
        </div>
    </article>
    <main class="page">
        <section class="main">
            <form action="{{ route('admin.about.reviews.update', ['review' => $review->id]) }}" method="POST">
                @csrf
                <h3 class="ui header header__title">Содержание</h3>
                <div class="page-block-titleInputText">
                    <h4 class="ui header header__subtitle page__icon_question">Имя автора</h4>
                    <div class="sub header header__subheader">Пояснение</div>
                    <div class="ui input">
                        <input type="text" name="author" value="{{ $review->author }}"/>
                    </div>
                </div>
                <div class="page-block-titleAreaText">
                    <h4 class="ui header header__subtitle">Отзыв</h4>
                    <div class="sub header header__subheader">Пояснение</div>
                    <textarea class="ui segment textEditor"
                              name="description">{{ $review->description }}</textarea>
                    <button type="submit" class="ui blue button">Обновить</button>
                </div>
            </form>
        </section>
    </main>
@endsection

www/resources/views/admin/pages/about/team.blade.php
@extends('admin.layouts.app')

@section('content')
    @include('admin.partials.sidebar')
    <article class="article">
        @include('admin.partials.header')
        <div class="header__sub">
            <div class="sub header">изменение работника</div>
            <h1 class="ui header">ИЗМЕНЕНИЕ РАБОТНИКА {{ $team->name_ru }} ({{ $team->name_eng }})</h1>
            <h2 class="sub header">
                <span>
                    <a href="{{ route('admin.about.index') }}">О КОМПАНИИ</a>
                    /
                    КОМАНДА
                    /
                    ИЗМЕНЕНИЕ РАБОТНИКА {{ $team->name_ru }} ({{ $team->name_eng }})
                </span>
            </h2>
        </div>
    </article>
    <main class="page">
        <section class="main">
            <form action="{{ route('admin.about.team.update', ['team' => $team->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                <h3 class="ui header header__title">Содержание</h3>
                <div class="page-block-titleInputText">
                    <h4 class="ui header header__subtitle page__icon_question">Имя автора</h4>
                    <div class="sub header header__subheader">Пояснение</div>
                    <div class="ui input">
                        <input type="text" name="name_ru" value="{{ $team->name_ru }}"/>
                    </div>
                </div>
                <div class="page-block-titleInputText">
                    <h4 class="ui header header__subtitle page__icon_question">Имя автора</h4>
                    <div class="sub header header__subheader">Пояснение</div>
                    <div class="ui input">
                        <input type="text" name="name_eng" value="{{ $team->name_eng }}"/>
                    </div>
                </div>
                <img class="page__img" src="{{ asset($team->image_first) }}" alt=""/>
                <img class="page__img" src="{{ asset($team->image_second) }}" alt=""/>
                <div class="sub header header__subheader">Иллюстрацию вписать в габариты 230x153</div>
                <div class="page-block-titleBtnText__btns">
                    <div class="ui action input">
                        <input type="text" placeholder="Загрузить файл"/>
                        <input type="file" value="{{ $team->image_first }}" name="image_first"/>
                        <a class="ui blue button fileUpload">Выбрать</a>
                    </div>
                    <div class="sub header header__subheader">Иллюстрацию вписать в габариты 230x153</div>
                    <div class="page-block-titleBtnText__btns">
                        <div class="ui action input">
                            <input type="text" placeholder="Загрузить файл"/>
                            <input type="file" name="image_second"/>
                            <a class="ui blue button fileUpload">Выбрать</a>
                        </div>
                        <button type="submit" class="ui blue button">Обновить</button>
                    </div>
                </div>
            </form>
        </section>
    </main>
@endsection