www/routes/web.php
<?php

use App\Http\Controllers\Admin\OptionController;
use Illuminate\Support\Facades\App as Locale;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Models\Page;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
$locale = Locale::currentLocale();

Auth::routes(['register' => false]);
Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

Route::group(['prefix' => '{locale?}', 'middleware' => 'locale'], function ($locale) {
    Route::get('', [App\Http\Controllers\PageController::class, 'index'])->name('index');
    Route::get('/about', [App\Http\Controllers\PageController::class, 'about'])->name('about');
    Route::post('/about/review/add',
        [\App\Http\Controllers\PageController::class, 'createReview'])->name('review.create');
    Route::get('/download/{file}',
        [App\Http\Controllers\PageController::class, 'aboutGetFile'])->name('about.get-file');
    Route::get('/event', [App\Http\Controllers\PageController::class, 'event'])->name('event');

    Route::get('/mconsult', [App\Http\Controllers\PageController::class, 'mconsult'])->name('mconsult');
    Route::get('/registration-and-accreditation',
        [\App\Http\Controllers\PageController::class, 'registrationAccreditation'])->name('accreditation');
    Route::get('/relocation-services', [\App\Http\Controllers\PageController::class, 'relocation'])->name('relocation');
    Route::get('/travel-and-leisure', [\App\Http\Controllers\PageController::class, 'travel'])->name('travel');
    Route::get('/visa-support', [\App\Http\Controllers\PageController::class, 'visa'])->name('visa');
    Route::get('/{number}/inner',
        [App\Http\Controllers\PageController::class, 'mconsultInner'])->name('mconsult-inner');
    Route::get('/sale/{number}',
        [App\Http\Controllers\PageController::class, 'mconsultSale'])->name('mconsult.sale');
    Route::get('/news', [App\Http\Controllers\PageController::class, 'news'])->name('news');
    Route::get('/publication', [App\Http\Controllers\PageController::class, 'publication'])->name('publication');
    Route::get('/sale', [App\Http\Controllers\PageController::class, 'sale'])->name('sale');

    Route::group(['prefix' => '/inform-agency', 'as' => 'inform-agency.'], function ($locale) {
        Route::get('', [App\Http\Controllers\InformAgency\PageController::class, 'index'])->name('index');
        Route::get('/news', [App\Http\Controllers\InformAgency\PageController::class, 'news'])->name('news');
        Route::get('/publications',
            [App\Http\Controllers\InformAgency\PageController::class, 'publications'])->name('publications');
        Route::get('/events', [App\Http\Controllers\InformAgency\PageController::class, 'events'])->name('events');
        Route::get('/inform-agency/{type}/{agency}',
            [App\Http\Controllers\InformAgency\PageController::class, 'item'])->name('item');
    });
    Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('show.login');
});

Route::get('{locale?}/admin', function () {
    return redirect()->route('admin.main.index');
});

Route::get('/admin', function () {
    return redirect()->route('admin.main.index');
});

Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => '/main', 'as' => 'main.'], function () {
        Route::get('', [App\Http\Controllers\Admin\MainController::class, 'index'])->name('index');
        Route::post('text/store/{lang}',
            [App\Http\Controllers\Admin\MainController::class, 'textStore'])->name('store');
        Route::post('/clients/store',
            [App\Http\Controllers\Admin\MainController::class, 'clientStore'])->name('clients.store');
        Route::get('/clients/{client}',
            [App\Http\Controllers\Admin\MainController::class, 'clientEdit'])->name('clients.edit');
        Route::post('/clients/{client}/update',
            [App\Http\Controllers\Admin\MainController::class, 'clientUpdate'])->name('clients.update');
        Route::post('/clients/{client}/delete',
            [App\Http\Controllers\Admin\MainController::class, 'clientDelete'])->name('clients.delete');
    });

    Route::group(['prefix' => '/about-us', 'as' => 'about.'], function () {
        Route::get('', [App\Http\Controllers\Admin\AboutController::class, 'index'])->name('index');
        Route::post('/meta/store/{lang}',
            [App\Http\Controllers\Admin\AboutController::class, 'metaStore'])->name('meta.store');
        Route::group(['prefix' => '/reviews', 'as' => 'reviews.'], function () {
            Route::get('/{review}',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewEdit'])->name('edit');
            Route::post('/{review}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewUpdate'])->name('update');
            Route::delete('/{review}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'reviewDelete'])->name('delete');
        });
        Route::group(['prefix' => '/team', 'as' => 'team.'], function () {
            Route::get('/{team}',
                [App\Http\Controllers\Admin\AboutController::class, 'teamEdit'])->name('edit');
            Route::post('/{team}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'teamUpdate'])->name('update');
            Route::delete('/{team}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'teamDelete'])->name('delete');
        });
        Route::group(['prefix' => '/certificate', 'as' => 'certificate.'], function () {
            Route::get('/add',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateAdd'])->name('add');
            Route::post('/store',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateStore'])->name('store');
            Route::get('/{certificate}',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateEdit'])->name('edit');
            Route::post('/{certificate}/update',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateUpdate'])->name('update');
            Route::delete('/{certificate}/delete',
                [App\Http\Controllers\Admin\AboutController::class, 'certificateDelete'])->name('delete');
        });
    });

    Route::group(['prefix' => '/'.Page::PAGE_SRVM, 'as' => 'srvm.'], function () {
        Route::get('', [App\Http\Controllers\Admin\SRVMController::class, 'index'])->name('index');
    });;
    Route::group(['prefix' => '/'.Page::PAGE_VISA_SUPPORT, 'as' => 'visa.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\VisaSupportController::class, 'index'])->name('index');
        Route::get('{country}/edit',
            [\App\Http\Controllers\Admin\CountryController::class, 'edit'])->name('country.edit');
        Route::post('{country}/update',
            [\App\Http\Controllers\Admin\CountryController::class, 'update'])->name('country.update');
        Route::post('country/store',
            [\App\Http\Controllers\Admin\CountryController::class, 'store'])->name('country.store');
    });

    Route::group(['prefix' => '/'.Page::PAGE_RELOCATION, 'as' => 'relocation.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\RelocationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_REGISTRY_ACCREDITATION, 'as' => 'accreditation.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\RegitstryAccreditationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_TRAVEL_RELAXATION, 'as' => 'travel.'], function () {
        Route::get('',
            [App\Http\Controllers\Admin\TravelRelaxationController::class, 'index'])->name('index');
    });

    Route::group(['prefix' => '/'.Page::PAGE_INFORM_AGENCY, 'as' => 'agency.'], function () {
        Route::get('', [App\Http\Controllers\Admin\InformAgencyController::class, 'index'])->name('index');
        Route::get('{number}', [\App\Http\Controllers\Admin\InformAgencyController::class, 'edit'])->name('edit');
        Route::post('{agency}/update',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'update'])->name('update');
        Route::post('{number}/image/update',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'updateImage'])->name('update.image');
        Route::get('{number}/{type}/add',
            [\App\Http\Controllers\Admin\InformAgencyController::class, 'add'])->name('add');
        Route::post('create', [\App\Http\Controllers\Admin\InformAgencyController::class, 'create'])->name('create');
    });

    Route::group(['prefix' => '/options', 'as' => 'option.'], function () {
        Route::get('', [App\Http\Controllers\Admin\OptionController::class, 'index'])->name('index');
        Route::get('{key}/edit', [App\Http\Controllers\Admin\OptionController::class, 'edit'])->name('edit');

        Route::post('{key}/update', [App\Http\Controllers\Admin\OptionController::class, 'update'])->name('update');
    });

    Route::get('/information-support',
        [App\Http\Controllers\Admin\PageController::class, 'informationSupport'])->name('information-support');
    Route::get('/luxembourg', [App\Http\Controllers\Admin\PageController::class, 'luxembourg'])->name('luxembourg');
    Route::get('/package-services',
        [App\Http\Controllers\Admin\PageController::class, 'packageServices'])->name('package-services');

www/resources/views/admin/partials/header.blade.php
<header class="ui header header__top"><a class="header_back" href="/">< назад </a>
    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
        @csrf
        <a class="header_admin"
           href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">administrator</a>
    </form>
</header>

www/resources/views/admin/partials/sidebar.blade.php
<aside class="sidebar">
    <div class="ui sidebar inverted vertical menu ui visible sidebar">
        <div class="item">
            <div class="sidebar__logo"><img src="{{ asset('images/logo-main-sidebar.svg') }}" alt="logo"/></div>
        </div>
        <div class="item"><a class="item active" href="{{ route('admin.main.index') }}">Главная</a><a class="item"
                                                                                                      href="{{ route('admin.about.index') }}">О
                компании</a></div>
        <div class="item">
            <div class="subtitle">УСЛУГИ</div>
            <a class="item" href="{{ route('admin.srvm.index') }}"> Миграционный консалтинг</a>
            <div class="menu">
                <a class="item"
                   href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_SRVM, 'category' => 'vks']) }}">ВКС</a>
                <a class="item"
                   href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_SRVM, 'category' => 'vig-op']) }}">
                    Визовые иностранные граждане, общий порядок</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_SRVM, 'category' => 'bvig-op']) }}"
                   class="item">
                    Безвизовые иностранные граждане, общий порядок</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_SRVM, 'category' => 'akkreditovannye-sotrudniki']) }}"
                   class="item">
                    Аккредитованные сотрудники</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_SRVM, 'category' => 'v-ramkah-soglashenij-s-franciej-i-yuzhnoj-koreej']) }}"
                   class="item">
                    В рамках соглашений с Францией и Южной Кореей</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_SRVM, 'category' => 'razreshenie-na-vremennoe-prozhivanie']) }}"
                   class="item">Разрешение на временное проживание</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_SRVM, 'category' => 'vid-na-zhitelstvo']) }}"
                   class="item">
                    Вид на жительство</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_SRVM, 'category' => 'prochie']) }}"
                   class="item">Прочие</a>
                <a class="item"
                   href="{{ route('admin.service-type.sale.index', ['page' => \App\Models\Page::PAGE_SRVM]) }}">
                    Специальные предложения и акции</a>
            </div>
        </div>
        <div class="item">
            <a class="item" href="{{ route('admin.visa.index') }}">ВИЗОВАЯ ПОДДЕРЖКА</a>
            <div class="menu">
                <a href="{{ route('admin.service-type.sale.index', ['page' => \App\Models\Page::PAGE_VISA_SUPPORT]) }}" class="item">
                    Специальные предложения и акции</a>
            </div>
        </div>
        <div class="item">
            <a class="item" href="{{ route('admin.relocation.index') }}">Релокационные услуги</a>
            <div class="menu">
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_RELOCATION, 'category' => 'paketnye-uslugi']) }}"
                   class="item">
                    Пакетные услуги</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_RELOCATION, 'category' => 'otdelnye-servisy']) }}"
                   class="item">
                    Отдельные сервисы</a>
                <a href="{{ route('admin.service-type.sale.index', ['page' => \App\Models\Page::PAGE_RELOCATION]) }}" class="item">
                    Специальные предложения и акции</a>
            </div>
        </div>
        <div class="item">
            <a class="item" href="{{ route('admin.accreditation.index') }}">Регистрация и аккредитация</a>
            <div class="menu">
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_REGISTRY_ACCREDITATION,
                    'category' => 'akkreditaciya-predstavitelstvi-filialov-inostrannyh-kompanij']) }}"
                   class="item">Аккредитация представительств и филиалов иностранных компаний</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_REGISTRY_ACCREDITATION, 'category' => 'registraciya-rossijskih-kompanij']) }}"
                   class="item">Регистрация российских компаний</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_REGISTRY_ACCREDITATION, 'category' => 'prochie-uslugi']) }}"
                   class="item">
                    Прочие услуги</a>
                <a href="{{ route('admin.service-type.sale.index', ['page' => \App\Models\Page::PAGE_REGISTRY_ACCREDITATION]) }}"
                   class="item">Специальные предложения и акции</a></div>
        </div>
        <div class="item">
            <a class="item" href="{{ route('admin.travel.index') }}">Путешествия и отдых</a>
            <div class="menu">
                <a href="{{ route('admin.service-type.sale.index', ['page' => \App\Models\Page::PAGE_TRAVEL_RELAXATION]) }}"
                   class="item">Специальные предложения и акции</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_TRAVEL_RELAXATION, 'category' => 'turi']) }}"
                   class="item">Туры</a>
                <a href="{{ route('admin.service-type.index', ['page' => \App\Models\Page::PAGE_TRAVEL_RELAXATION, 'category' => 'otdelnye-servisy']) }}"
                   class="item">Отдельные сервисы</a>
            </div>
        </div>
        <div class="item">
            <a href="{{ route('admin.agency.index') }}" class="item">ИНФОРМАГЕНТСТВО</a>
        </div>
        <div class="item">
            <a href="{{ route('admin.option.index') }}" class="item">Настройки Мета-тегов</a>
        </div>

    </div>
</aside>